// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Buildings = sequelize.define('buildings', {
    name: {
      type: DataTypes.STRING,
    },
    addressLine1: {
      type: DataTypes.STRING,
      field: 'address_line_1',
    },
    number: {
      type: DataTypes.INTEGER,
    },
    centralHeating: {
      type: DataTypes.BOOLEAN,
    },
  }, {
    tableName: 'buildings',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Buildings.associate = (models) => {
    Buildings.belongsTo(models.properties, {
      foreignKey: {
        name: 'propertyIdKey',
        field: 'property_id',
      },
      as: 'property',
    });
    Buildings.hasMany(models.lots, {
      foreignKey: {
        name: 'buildingIdKey',
        field: 'building_id',
      },
      as: 'lots',
    });
  };

  return Buildings;
};
