// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const RepartitionKeys = sequelize.define('repartitionKeys', {
    name: {
      type: DataTypes.STRING,
    },
    total: {
      type: DataTypes.BIGINT,
    },
  }, {
    tableName: 'repartition_keys',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  RepartitionKeys.associate = (models) => {
    RepartitionKeys.belongsTo(models.properties, {
      foreignKey: {
        name: 'propertyIdKey',
        field: 'property_id',
      },
      as: 'property',
    });
  };

  return RepartitionKeys;
};
